//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uvelir.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ArticulNumber { get; set; }
        public string Title { get; set; }
        public string Unit { get; set; }
        public decimal Count { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public int IDCategoryProduct { get; set; }
        public int Discount { get; set; }
        public int QuantitiInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
    }
}
